package dev.pgm.roadmate.utils

/**
 * Every fixed line RoadMate says or shows that isn't generated by Gemini —
 * one place, one voice ("calm co-driver, short, no filler"). The domain and
 * data layers have no Android `Context`, so these can't be string resources;
 * centralising them here is the equivalent. Screen chrome (buttons, labels)
 * lives in `strings.xml` instead.
 */
object SpokenText {

    // Calls
    const val CALL_NO_PERMISSION =
        "No puedo llamar sin permiso. Actívalo en ajustes: contactos y teléfono."
    fun calling(name: String) = "Llamando a $name"
    const val CALL_AMBIGUOUS = "Tienes varios contactos con ese nombre. Dime cuál."
    fun callWhichNumber(name: String, options: List<String>) =
        "$name tiene varios números: ${options.joinToString(" o ")}. ¿Cuál?"
    fun contactNotFound(name: String) = "No encuentro a $name en tus contactos."
    fun unknownRelation(relation: String) =
        "No sé quién es tu $relation. Dime antes \"nombre es mi $relation\"."

    // Map search
    fun searchingMap(query: String) = "Busco $query en el mapa."
    fun noMapsApp(query: String) = "No hay ninguna app de mapas para buscar $query."

    // Media
    fun openingApp(app: String) = "Abro $app."
    fun cantOpenApp(app: String) = "No puedo abrir $app. ¿La tienes instalada?"

    // Memory
    const val NOTED = "Anotado."
    const val FORGOTTEN = "Vale, lo olvido."
    const val NOTHING_TO_FORGET = "No tenía nada apuntado sobre eso."
    const val NOTHING_LEARNED = "Aún no he aprendido nada sobre ti."
    fun known(items: String) = "Recuerdo esto: $items."
    fun relationSaved(name: String, relation: String) = "Vale, $name es tu $relation."
    fun locationSaved(label: String) = "Guardado. Esta es tu $label."
    const val NO_LOCATION_YET = "No tengo tu ubicación ahora mismo. Dímelo cuando tenga señal."
    fun recalled(question: String, answer: String) = "Me preguntaste \"$question\" y te dije: $answer"
    const val NOTHING_ON_RECORD = "No encuentro que hayamos hablado de eso."

    // Speech recognition
    const val SPEECH_FLOW_ERROR = "No te he oído. Prueba otra vez."
    const val SPEECH_NOT_READY = "La voz aún se está preparando. Prueba en unos segundos."
    const val SPEECH_MIC_DENIED = "No tengo acceso al micrófono. Revisa el permiso."

    // Background rest reminder
    const val REST_NUDGE = "Llevas un buen rato al volante. ¿Paramos a descansar?"
    const val REST_MONITOR = "Atento por si necesitas un descanso."
}
