package dev.pgm.roadmate.utils

/**
 * Every fixed line RoadMate says or shows that isn't generated by Gemini —
 * one place, one voice ("calm co-driver, short, no filler"). The domain and
 * data layers have no Android `Context`, so these can't be string resources;
 * centralising them here is the equivalent. Screen chrome (buttons, labels)
 * lives in `strings.xml` instead.
 */
object SpokenText {

    /** Spoken right after "oye copiloto", before the mic opens for the question. */
    const val WAKE_ACK = "Sí, dime."

    // Calls
    const val CALL_NO_PERMISSION =
        "No puedo llamar sin permiso. Actívalo en ajustes: contactos y teléfono."
    fun calling(name: String) = "Llamando a $name"
    const val CALL_AMBIGUOUS = "Tienes varios contactos con ese nombre. Dime cuál."
    fun callWhichNumber(name: String, options: List<String>) =
        "$name tiene varios números: ${options.joinToString(" o ")}. ¿Cuál?"
    fun contactNotFound(name: String) = "No encuentro a $name en tus contactos."
    fun unknownRelation(relation: String) =
        "No sé quién es tu $relation. Dime antes \"nombre es mi $relation\"."

    // Map search — always on the downloaded offline map, never an external app
    fun searchingMap(query: String) = "Busco $query en el mapa."
    fun showingCategoryOnMap(query: String) = "Te enseño $query en el mapa."
    fun navigatingTo(query: String) = "Te llevo a $query. Mira el mapa."
    fun placeNotSet(label: String) =
        "No sé dónde está tu $label. Dime antes «esta es mi $label»."
    const val NO_OFFLINE_MAP =
        "No tengo un mapa descargado de esta zona. Descárgalo desde la pestaña Mapa."
    fun notOnOfflineMap(query: String) =
        "No encuentro $query en el mapa descargado."

    // Routing — spoken once the offline route is (or isn't) traced
    fun routeTraced(distance: String, duration: String) =
        "Ruta trazada: $distance, unos $duration."
    const val ROUTE_UNKNOWN_ORIGIN = "No sé dónde estás ahora mismo."
    const val ROUTE_NOT_POSSIBLE = "No puedo trazar la ruta con el mapa descargado."
    const val ROUTE_NEEDS_WIFI =
        "Conéctate a Wi-Fi para descargar el mapa de ruta de esta zona."
    const val ROUTE_DOWNLOAD_FAILED = "No pude descargar el mapa de ruta."

    // Weather
    fun weatherNow(description: String) = "Ahora mismo: $description."
    fun weatherAt(place: String, description: String) = "En $place: $description."
    fun weatherUnavailableFor(place: String) = "No consigo el tiempo de $place ahora mismo."
    const val WEATHER_UNAVAILABLE = "No puedo consultar el tiempo ahora mismo."

    // Media
    fun openingApp(app: String) = "Abro $app."

    /** "pon música" with no music app installed that RoadMate can open. */
    const val NO_MUSIC_APP = "No encuentro ninguna app de música que pueda abrir."
    fun cantOpenApp(app: String) = "No puedo abrir $app. ¿La tienes instalada?"

    // Memory
    const val NOTED = "Anotado."
    const val FORGOTTEN = "Vale, lo olvido."
    const val NOTHING_TO_FORGET = "No tenía nada apuntado sobre eso."
    const val NOTHING_LEARNED = "Aún no he aprendido nada sobre ti."
    fun known(items: String) = "Recuerdo esto: $items."
    fun relationSaved(name: String, relation: String) = "Vale, $name es tu $relation."
    fun locationSaved(label: String) = "Guardado. Esta es tu $label."
    const val NO_LOCATION_YET = "No tengo tu ubicación ahora mismo. Dímelo cuando tenga señal."
    fun recalled(question: String, answer: String) = "Me preguntaste \"$question\" y te dije: $answer"
    const val NOTHING_ON_RECORD = "No encuentro que hayamos hablado de eso."

    /** The answer pipeline itself failed — say so rather than going quiet. */
    const val ANSWER_FAILED = "Se me ha cruzado algo. Pregúntamelo otra vez."

    // Speech recognition
    const val SPEECH_FLOW_ERROR = "No te he oído. Prueba otra vez."
    const val SPEECH_NOT_READY = "La voz aún se está preparando. Prueba en unos segundos."
    const val SPEECH_MIC_DENIED = "No tengo acceso al micrófono. Revisa el permiso."

    // Background rest reminder
    const val REST_NUDGE = "Llevas un buen rato al volante. ¿Paramos a descansar?"
    const val REST_MONITOR = "Atento por si necesitas un descanso."
}
